# Database configuration
database:
  database: "MY_DB"

# Producer, Consumer threads configuration
producer_consumer:
  read_batch_size: 50000
  num_consumers: 50
  consumers_queue_size: 100  # 2 * num_consumers

# Database updater configuration
db_updater:
  update_queue_size: 100
  update_status: false

# ArsAdmin command configuration
arsadmin:
  command_max_objects: 10000
  dir_max_elems: 32000
  user: "arsuser"
  password: null  # Optional, can be null/omitted
  od_inst: "od_instance_name"
  base_dir: "/path/to/base/directory"

# Optional timeout in seconds (null means no timeout)
timeout_seconds: null  # Set to a number like 3600 for a 1-hour timeout